initial_positions:
  joint1: -1.751
  joint2: -0.342
  joint3: 1.656
  joint4: 1.036
  joint5: 0.360
  joint6: 0.074
  joint7: 1.570
  gripper: 0.0
  left_thumb_metacarpal_joint: 0.0
  left_thumb_proximal_joint: 0.0
  left_index_proximal_joint: 0.0
  left_middle_proximal_joint: 0.0
  left_ring_proximal_joint: 0.0
  left_pinky_proximal_joint: 0.0
  right_thumb_metacarpal_joint: 0.0
  right_thumb_proximal_joint: 0.0
  right_index_proximal_joint: 0.0
  right_middle_proximal_joint: 0.0
  right_ring_proximal_joint: 0.0
  right_pinky_proximal_joint: 0.0
